package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/justjundana/git-config-manager/internal/audit"
	"github.com/justjundana/git-config-manager/internal/keyledger"
	fileSvc "github.com/justjundana/git-config-manager/internal/service/file"
	"github.com/justjundana/git-config-manager/pkg/ui"

	"github.com/spf13/cobra"
)

func newSSHCleanCmd() *cobra.Command {
	var (
		yes    bool
		dryRun bool
	)

	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Remove GCM-generated SSH keys no longer used by any profile",
		Long: `Remove SSH keys that GCM generated but that are no longer referenced by any profile.

Only keys generated by GCM (recorded in the generated-keys ledger) are
considered. SSH keys you created yourself or that GCM merely linked to a
profile are never touched.

Examples:
  gcm ssh clean
  gcm ssh clean --dry-run
  gcm ssh clean --yes`,
		RunE: func(_ *cobra.Command, _ []string) error {
			data, err := ctr.KeyLedger.Load()
			if err != nil {
				return err
			}

			referenced, err := referencedSSHKeyPaths()
			if err != nil {
				return err
			}

			var orphans []keyledger.SSHEntry
			for _, entry := range data.SSH {
				if _, used := referenced[normalizeKeyPath(entry.KeyPath)]; used {
					continue
				}
				orphans = append(orphans, entry)
			}

			if len(orphans) == 0 {
				ui.Info("No unused GCM-generated SSH keys to clean")
				return nil
			}

			ui.Warning("The following GCM-generated SSH keys are not used by any profile:")
			ui.Blank()
			headers := []string{"Profile", "Key", "Fingerprint"}
			var rows [][]string
			for _, e := range orphans {
				rows = append(rows, []string{e.Profile, e.KeyPath, e.Fingerprint})
			}
			ui.SimpleTable(headers, rows)
			ui.Blank()

			if dryRun {
				ui.Info("Dry run — no keys were removed")
				return nil
			}

			if !yes {
				confirm, err := ui.AskConfirm(fmt.Sprintf("Delete these %d SSH key(s) from disk?", len(orphans)), false)
				if err != nil || !confirm {
					ui.Info("Cancelled")
					return nil
				}
			}

			removed := 0
			for _, e := range orphans {
				if err := removeSSHKeyFiles(e.KeyPath); err != nil {
					ui.Warning("Could not remove %s: %v", e.KeyPath, err)
					continue
				}
				ctr.SSHManager.RemoveFromAgent(e.KeyPath)
				if err := ctr.KeyLedger.RemoveSSH(e.KeyPath); err != nil {
					ui.Warning("Removed key files but could not update ledger for %s: %v", e.KeyPath, err)
				}
				ctr.AuditLogger.Log(audit.ActionSSHGenerate, e.Profile,
					map[string]string{"action": "clean", "path": e.KeyPath}, nil)
				ui.Success("Removed SSH key %s", e.KeyPath)
				removed++
			}

			ui.Blank()
			ui.Success("Cleaned %d SSH key(s)", removed)
			return nil
		},
	}

	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Show what would be removed without deleting anything")
	return cmd
}

func newGPGCleanCmd() *cobra.Command {
	var (
		yes    bool
		dryRun bool
	)

	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Remove GCM-generated GPG keys no longer used by any profile",
		Long: `Remove GPG keys that GCM generated but that are no longer referenced by any profile.

Only keys generated by GCM (recorded in the generated-keys ledger) are
considered. GPG keys you created yourself are never touched.

Examples:
  gcm gpg clean
  gcm gpg clean --dry-run
  gcm gpg clean --yes`,
		RunE: func(_ *cobra.Command, _ []string) error {
			data, err := ctr.KeyLedger.Load()
			if err != nil {
				return err
			}

			referenced, err := referencedGPGKeyIDs()
			if err != nil {
				return err
			}

			var orphans []keyledger.GPGEntry
			for _, entry := range data.GPG {
				if gpgKeyReferenced(entry, referenced) {
					continue
				}
				orphans = append(orphans, entry)
			}

			if len(orphans) == 0 {
				ui.Info("No unused GCM-generated GPG keys to clean")
				return nil
			}

			ui.Warning("The following GCM-generated GPG keys are not used by any profile:")
			ui.Blank()
			headers := []string{"Profile", "Key ID", "Fingerprint"}
			var rows [][]string
			for _, e := range orphans {
				rows = append(rows, []string{e.Profile, e.KeyID, e.Fingerprint})
			}
			ui.SimpleTable(headers, rows)
			ui.Blank()

			if dryRun {
				ui.Info("Dry run — no keys were removed")
				return nil
			}

			if !ctr.GPGManager.IsInstalled() {
				ui.Warning("GPG is not installed — cannot delete keys from the keyring")
				return nil
			}

			if !yes {
				confirm, err := ui.AskConfirm(fmt.Sprintf("Delete these %d GPG key(s) from the keyring?", len(orphans)), false)
				if err != nil || !confirm {
					ui.Info("Cancelled")
					return nil
				}
			}

			removed := 0
			for _, e := range orphans {
				if err := ctr.GPGManager.Delete(e.KeyID); err != nil {
					ui.Warning("Could not delete GPG key %s: %v", e.KeyID, err)
					continue
				}
				if err := ctr.KeyLedger.RemoveGPG(e.KeyID); err != nil {
					ui.Warning("Deleted key but could not update ledger for %s: %v", e.KeyID, err)
				}
				ctr.AuditLogger.Log(audit.ActionGPGGenerate, e.Profile,
					map[string]string{"action": "clean", "key_id": e.KeyID}, nil)
				ui.Success("Removed GPG key %s", e.KeyID)
				removed++
			}

			ui.Blank()
			ui.Success("Cleaned %d GPG key(s)", removed)
			return nil
		},
	}

	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Skip confirmation")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Show what would be removed without deleting anything")
	return cmd
}

// referencedSSHKeyPaths returns the set of normalized private-key paths
// currently referenced by any profile.
func referencedSSHKeyPaths() (map[string]struct{}, error) {
	profiles, err := ctr.ProfileManager.List()
	if err != nil {
		return nil, err
	}
	referenced := make(map[string]struct{})
	for _, p := range profiles {
		if p.SSH != nil && strings.TrimSpace(p.SSH.KeyPath) != "" {
			referenced[normalizeKeyPath(p.SSH.KeyPath)] = struct{}{}
		}
	}
	return referenced, nil
}

// referencedGPGKeyIDs returns the set of GPG key IDs currently referenced by
// any profile.
func referencedGPGKeyIDs() (map[string]struct{}, error) {
	profiles, err := ctr.ProfileManager.List()
	if err != nil {
		return nil, err
	}
	referenced := make(map[string]struct{})
	for _, p := range profiles {
		if p.GPG != nil && strings.TrimSpace(p.GPG.KeyID) != "" {
			referenced[p.GPG.KeyID] = struct{}{}
		}
	}
	return referenced, nil
}

// gpgKeyReferenced reports whether the ledger entry matches any profile-referenced
// key ID. A profile may store a short key ID while the ledger holds a longer ID
// or fingerprint, so suffix matching is used in both directions.
func gpgKeyReferenced(entry keyledger.GPGEntry, referenced map[string]struct{}) bool {
	for ref := range referenced {
		if ref == entry.KeyID {
			return true
		}
		if entry.KeyID != "" && (strings.HasSuffix(entry.KeyID, ref) || strings.HasSuffix(ref, entry.KeyID)) {
			return true
		}
		if entry.Fingerprint != "" && strings.HasSuffix(entry.Fingerprint, ref) {
			return true
		}
	}
	return false
}

func normalizeKeyPath(path string) string {
	return filepath.Clean(fileSvc.ExpandPath(strings.TrimSpace(path)))
}

func removeSSHKeyFiles(keyPath string) error {
	expanded := fileSvc.ExpandPath(keyPath)
	var firstErr error
	if err := os.Remove(expanded); err != nil && !os.IsNotExist(err) {
		firstErr = err
	}
	if err := os.Remove(expanded + ".pub"); err != nil && !os.IsNotExist(err) && firstErr == nil {
		firstErr = err
	}
	return firstErr
}
