// Package keyledger records the SSH and GPG keys that GCM itself generated.
//
// GCM can both generate new keys and adopt pre-existing keys for a profile.
// When cleaning up unused keys we must only ever delete key material that GCM
// created — never a key the user already had on their system. The ledger is the
// source of truth for that distinction: an entry exists if and only if GCM
// generated the key. Adopted/pre-existing keys are never recorded and are
// therefore always ignored by `gcm ssh clean` / `gcm gpg clean`.
package keyledger

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	_config "github.com/justjundana/git-config-manager/internal/config"
	_file "github.com/justjundana/git-config-manager/internal/service/file"
)

// fileName is the ledger file stored under the GCM data directory.
const fileName = "generated-keys.json"

// Test hooks for deterministic error-path testing.
var (
	readFileFn   = os.ReadFile
	mkdirAllFn   = os.MkdirAll
	marshalFn    = json.MarshalIndent
	createTempFn = func(dir, pattern string) (tempFile, error) { return os.CreateTemp(dir, pattern) }
	statFn       = os.Stat
	removeFn     = os.Remove
	renameFn     = os.Rename
)

// tempFile is the subset of *os.File used by saveLocked. It allows tests to
// substitute a fake that fails at specific steps.
type tempFile interface {
	Name() string
	Write([]byte) (int, error)
	Chmod(os.FileMode) error
	Sync() error
	Close() error
}

// SSHEntry records a single SSH key pair generated by GCM.
type SSHEntry struct {
	// Profile is the profile the key was generated for at creation time.
	Profile string `json:"profile"`
	// KeyPath is the absolute path to the private key file.
	KeyPath string `json:"key_path"`
	// Fingerprint is the SHA256 fingerprint of the public key.
	Fingerprint string `json:"fingerprint,omitempty"`
	// CreatedAt is when GCM generated the key.
	CreatedAt time.Time `json:"created_at"`
}

// GPGEntry records a single GPG key generated by GCM.
type GPGEntry struct {
	// Profile is the profile the key was generated for at creation time.
	Profile string `json:"profile"`
	// KeyID is the GPG key ID.
	KeyID string `json:"key_id"`
	// Fingerprint is the full GPG fingerprint, when known.
	Fingerprint string `json:"fingerprint,omitempty"`
	// CreatedAt is when GCM generated the key.
	CreatedAt time.Time `json:"created_at"`
}

// Data is the on-disk ledger structure.
type Data struct {
	SSH []SSHEntry `json:"ssh"`
	GPG []GPGEntry `json:"gpg"`
}

// Ledger provides serialized access to the generated-keys ledger.
type Ledger struct {
	mu   sync.Mutex
	path string
}

// New creates a Ledger backed by the default file under the GCM data directory.
func New() *Ledger {
	return &Ledger{path: filepath.Join(_config.GCMDir(), fileName)}
}

// NewWithPath creates a Ledger backed by an explicit file path. Intended for
// tests.
func NewWithPath(path string) *Ledger {
	return &Ledger{path: path}
}

// Load reads the ledger from disk. A missing file yields an empty ledger.
func (l *Ledger) Load() (*Data, error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.loadLocked()
}

func (l *Ledger) loadLocked() (*Data, error) {
	data, err := readFileFn(l.path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Data{}, nil
		}
		return nil, fmt.Errorf("reading key ledger: %w", err)
	}

	var d Data
	if len(data) == 0 {
		return &Data{}, nil
	}
	if err := json.Unmarshal(data, &d); err != nil {
		return nil, fmt.Errorf("parsing key ledger: %w", err)
	}
	return &d, nil
}

// save writes the ledger to disk atomically with 0600 permissions.
func (l *Ledger) saveLocked(d *Data) error {
	dir := filepath.Dir(l.path)
	if err := mkdirAllFn(dir, 0o700); err != nil {
		return fmt.Errorf("creating ledger directory: %w", err)
	}

	out, err := marshalFn(d, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling key ledger: %w", err)
	}

	tmp, err := createTempFn(dir, ".gcm-keyledger-*")
	if err != nil {
		return fmt.Errorf("creating temp ledger file: %w", err)
	}
	tmpPath := tmp.Name()
	defer func() {
		if _, statErr := statFn(tmpPath); statErr == nil {
			_ = removeFn(tmpPath)
		}
	}()

	if _, err := tmp.Write(out); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("writing ledger file: %w", err)
	}
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("setting ledger permissions: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("syncing ledger file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("closing ledger file: %w", err)
	}
	if err := renameFn(tmpPath, l.path); err != nil {
		return fmt.Errorf("writing ledger file: %w", err)
	}
	return nil
}

// AddSSH records an SSH key generated by GCM. If an entry with the same key
// path already exists it is replaced.
func (l *Ledger) AddSSH(entry SSHEntry) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	d, err := l.loadLocked()
	if err != nil {
		return err
	}
	if entry.CreatedAt.IsZero() {
		entry.CreatedAt = time.Now().UTC()
	}

	filtered := d.SSH[:0]
	for _, e := range d.SSH {
		if e.KeyPath != entry.KeyPath {
			filtered = append(filtered, e)
		}
	}
	d.SSH = append(filtered, entry)
	sort.Slice(d.SSH, func(i, j int) bool { return d.SSH[i].KeyPath < d.SSH[j].KeyPath })
	return l.saveLocked(d)
}

// AddGPG records a GPG key generated by GCM. If an entry with the same key ID
// already exists it is replaced.
func (l *Ledger) AddGPG(entry GPGEntry) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	d, err := l.loadLocked()
	if err != nil {
		return err
	}
	if entry.CreatedAt.IsZero() {
		entry.CreatedAt = time.Now().UTC()
	}

	filtered := d.GPG[:0]
	for _, e := range d.GPG {
		if e.KeyID != entry.KeyID {
			filtered = append(filtered, e)
		}
	}
	d.GPG = append(filtered, entry)
	sort.Slice(d.GPG, func(i, j int) bool { return d.GPG[i].KeyID < d.GPG[j].KeyID })
	return l.saveLocked(d)
}

// RemoveSSH removes the SSH entry with the given key path. It is a no-op if no
// such entry exists.
// HasSSH reports whether keyPath was generated by GCM and is therefore safe to
// delete. Paths are compared after ~ expansion and cleaning, because a profile
// may store "~/.ssh/id_ed25519_work" while the ledger holds the absolute path.
func (l *Ledger) HasSSH(keyPath string) (bool, error) {
	d, err := l.Load()
	if err != nil {
		return false, err
	}
	want := normalizeLedgerPath(keyPath)
	if want == "" {
		return false, nil
	}
	for _, e := range d.SSH {
		if normalizeLedgerPath(e.KeyPath) == want {
			return true, nil
		}
	}
	return false, nil
}

// HasGPG reports whether keyID was generated by GCM and is therefore safe to
// delete.
//
// Matching is exact (trimmed, case-insensitive) rather than the suffix match
// used when deciding whether a key is still referenced. The two questions have
// opposite failure directions: a loose match there keeps an extra key, while a
// loose match here would authorise deleting a secret key the user created.
func (l *Ledger) HasGPG(keyID string) (bool, error) {
	d, err := l.Load()
	if err != nil {
		return false, err
	}
	want := strings.ToUpper(strings.TrimSpace(keyID))
	if want == "" {
		return false, nil
	}
	for _, e := range d.GPG {
		if strings.ToUpper(strings.TrimSpace(e.KeyID)) == want {
			return true, nil
		}
	}
	return false, nil
}

// normalizeLedgerPath makes two spellings of the same key path comparable.
func normalizeLedgerPath(p string) string {
	trimmed := strings.TrimSpace(p)
	if trimmed == "" {
		return ""
	}
	return filepath.Clean(_file.ExpandPath(trimmed))
}

func (l *Ledger) RemoveSSH(keyPath string) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	d, err := l.loadLocked()
	if err != nil {
		return err
	}
	filtered := d.SSH[:0]
	removed := false
	for _, e := range d.SSH {
		if e.KeyPath == keyPath {
			removed = true
			continue
		}
		filtered = append(filtered, e)
	}
	if !removed {
		return nil
	}
	d.SSH = filtered
	return l.saveLocked(d)
}

// RenameSSH moves the ledger entry for oldPath to newPath, preserving the
// profile, fingerprint and creation time. It is a no-op if no entry matches.
//
// GCM renames generated keys when a profile's provider layout changes. Without
// this the ledger keeps pointing at a path that no longer exists: the key loses
// its "generated by GCM" provenance, and a later "gcm ssh clean" drops the
// stale entry — after which anything the user places at the old path would be
// treated as GCM's to delete.
func (l *Ledger) RenameSSH(oldPath, newPath string) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	d, err := l.loadLocked()
	if err != nil {
		return err
	}

	want := normalizeLedgerPath(oldPath)
	target := normalizeLedgerPath(newPath)
	if want == "" || target == "" {
		return nil
	}

	renamed := false
	for i := range d.SSH {
		if normalizeLedgerPath(d.SSH[i].KeyPath) != want {
			continue
		}
		d.SSH[i].KeyPath = newPath
		renamed = true
	}
	if !renamed {
		return nil
	}

	sort.Slice(d.SSH, func(i, j int) bool { return d.SSH[i].KeyPath < d.SSH[j].KeyPath })
	return l.saveLocked(d)
}

// RemoveGPG removes the GPG entry with the given key ID. It is a no-op if no
// such entry exists.
func (l *Ledger) RemoveGPG(keyID string) error {
	l.mu.Lock()
	defer l.mu.Unlock()

	d, err := l.loadLocked()
	if err != nil {
		return err
	}
	filtered := d.GPG[:0]
	removed := false
	for _, e := range d.GPG {
		if e.KeyID == keyID {
			removed = true
			continue
		}
		filtered = append(filtered, e)
	}
	if !removed {
		return nil
	}
	d.GPG = filtered
	return l.saveLocked(d)
}
